export enum PointReason {
  JOIN_EVENT = 'JOIN_EVENT',
  CHECK_IN = 'CHECK_IN',
  COMPLETE_EVENT = 'COMPLETE_EVENT',
  STREAK_BONUS = 'STREAK_BONUS',
  REFERRAL = 'REFERRAL',
  MANUAL_ADJUSTMENT = 'MANUAL_ADJUSTMENT',
}
